/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "ibeam.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(IbeamMessage, IbeamMessage, AUTO)

PB_BIND(IbeamMessageData, IbeamMessageData, AUTO)

PB_BIND(PingRequest, PingRequest, AUTO)

PB_BIND(PingResponse, PingResponse, AUTO)

PB_BIND(GetRequest, GetRequest, AUTO)

PB_BIND(SetRequest, SetRequest, AUTO)

PB_BIND(ParameterResponse, ParameterResponse, AUTO)

PB_BIND(Parameter, Parameter, AUTO)

PB_BIND(ParamOption, ParamOption, AUTO)
