/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_LIB_IBEAM_IBEAM_PB_H_INCLUDED
#define PB_LIB_IBEAM_IBEAM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Parameter_paramType {
    Parameter_paramType_numberType = 0,
    Parameter_paramType_floatingType = 1,
    Parameter_paramType_optType = 2
} Parameter_paramType;

/* Struct definitions */
typedef struct _IbeamMessage {
    pb_callback_t data;
} IbeamMessage;

typedef struct _GetRequest {
    int32_t valueId;
} GetRequest;

typedef struct _ParamOption {
    int32_t optionId;
    pb_callback_t optionValue;
} ParamOption;

typedef struct _Parameter {
    int32_t number;
    float floating;
    pb_callback_t options;
} Parameter;

typedef struct _PingRequest {
    int32_t pingCounter;
} PingRequest;

typedef struct _PingResponse {
    int32_t pongCounter;
} PingResponse;

typedef struct _ParameterResponse {
    int32_t valueId;
    bool has_param;
    Parameter param;
} ParameterResponse;

typedef struct _SetRequest {
    int32_t valueId;
    bool has_param;
    Parameter param;
} SetRequest;

typedef struct _IbeamMessageData {
    pb_size_t which_data;
    union {
        GetRequest get;
        SetRequest set;
        ParameterResponse param;
    } data;
} IbeamMessageData;


/* Helper constants for enums */
#define _Parameter_paramType_MIN Parameter_paramType_numberType
#define _Parameter_paramType_MAX Parameter_paramType_optType
#define _Parameter_paramType_ARRAYSIZE ((Parameter_paramType)(Parameter_paramType_optType+1))


/* Initializer values for message structs */
#define IbeamMessage_init_default                {{{NULL}, NULL}}
#define IbeamMessageData_init_default            {0, {GetRequest_init_default}}
#define PingRequest_init_default                 {0}
#define PingResponse_init_default                {0}
#define GetRequest_init_default                  {0}
#define SetRequest_init_default                  {0, false, Parameter_init_default}
#define ParameterResponse_init_default           {0, false, Parameter_init_default}
#define Parameter_init_default                   {0, 0, {{NULL}, NULL}}
#define ParamOption_init_default                 {0, {{NULL}, NULL}}
#define IbeamMessage_init_zero                   {{{NULL}, NULL}}
#define IbeamMessageData_init_zero               {0, {GetRequest_init_zero}}
#define PingRequest_init_zero                    {0}
#define PingResponse_init_zero                   {0}
#define GetRequest_init_zero                     {0}
#define SetRequest_init_zero                     {0, false, Parameter_init_zero}
#define ParameterResponse_init_zero              {0, false, Parameter_init_zero}
#define Parameter_init_zero                      {0, 0, {{NULL}, NULL}}
#define ParamOption_init_zero                    {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define IbeamMessage_data_tag                    1
#define GetRequest_valueId_tag                   1
#define ParamOption_optionId_tag                 1
#define ParamOption_optionValue_tag              2
#define Parameter_number_tag                     1
#define Parameter_floating_tag                   2
#define Parameter_options_tag                    3
#define PingRequest_pingCounter_tag              1
#define PingResponse_pongCounter_tag             1
#define ParameterResponse_valueId_tag            1
#define ParameterResponse_param_tag              2
#define SetRequest_valueId_tag                   1
#define SetRequest_param_tag                     2
#define IbeamMessageData_get_tag                 1
#define IbeamMessageData_set_tag                 2
#define IbeamMessageData_param_tag               3

/* Struct field encoding specification for nanopb */
#define IbeamMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1)
#define IbeamMessage_CALLBACK pb_default_field_callback
#define IbeamMessage_DEFAULT NULL

#define IbeamMessageData_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,get,data.get),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,set,data.set),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,param,data.param),   3)
#define IbeamMessageData_CALLBACK NULL
#define IbeamMessageData_DEFAULT NULL
#define IbeamMessageData_data_get_MSGTYPE GetRequest
#define IbeamMessageData_data_set_MSGTYPE SetRequest
#define IbeamMessageData_data_param_MSGTYPE ParameterResponse

#define PingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    pingCounter,       1)
#define PingRequest_CALLBACK NULL
#define PingRequest_DEFAULT NULL

#define PingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    pongCounter,       1)
#define PingResponse_CALLBACK NULL
#define PingResponse_DEFAULT NULL

#define GetRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    valueId,           1)
#define GetRequest_CALLBACK NULL
#define GetRequest_DEFAULT NULL

#define SetRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    valueId,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  param,             2)
#define SetRequest_CALLBACK NULL
#define SetRequest_DEFAULT NULL
#define SetRequest_param_MSGTYPE Parameter

#define ParameterResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    valueId,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  param,             2)
#define ParameterResponse_CALLBACK NULL
#define ParameterResponse_DEFAULT NULL
#define ParameterResponse_param_MSGTYPE Parameter

#define Parameter_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    number,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    floating,          2) \
X(a, CALLBACK, REPEATED, MESSAGE,  options,           3)
#define Parameter_CALLBACK pb_default_field_callback
#define Parameter_DEFAULT NULL
#define Parameter_options_MSGTYPE ParamOption

#define ParamOption_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    optionId,          1) \
X(a, CALLBACK, SINGULAR, STRING,   optionValue,       2)
#define ParamOption_CALLBACK pb_default_field_callback
#define ParamOption_DEFAULT NULL

extern const pb_msgdesc_t IbeamMessage_msg;
extern const pb_msgdesc_t IbeamMessageData_msg;
extern const pb_msgdesc_t PingRequest_msg;
extern const pb_msgdesc_t PingResponse_msg;
extern const pb_msgdesc_t GetRequest_msg;
extern const pb_msgdesc_t SetRequest_msg;
extern const pb_msgdesc_t ParameterResponse_msg;
extern const pb_msgdesc_t Parameter_msg;
extern const pb_msgdesc_t ParamOption_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define IbeamMessage_fields &IbeamMessage_msg
#define IbeamMessageData_fields &IbeamMessageData_msg
#define PingRequest_fields &PingRequest_msg
#define PingResponse_fields &PingResponse_msg
#define GetRequest_fields &GetRequest_msg
#define SetRequest_fields &SetRequest_msg
#define ParameterResponse_fields &ParameterResponse_msg
#define Parameter_fields &Parameter_msg
#define ParamOption_fields &ParamOption_msg

/* Maximum encoded size of messages (where known) */
/* IbeamMessage_size depends on runtime parameters */
/* IbeamMessageData_size depends on runtime parameters */
#define PingRequest_size                         11
#define PingResponse_size                        11
#define GetRequest_size                          11
/* SetRequest_size depends on runtime parameters */
/* ParameterResponse_size depends on runtime parameters */
/* Parameter_size depends on runtime parameters */
/* ParamOption_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
